### ISSUE TITLE
Implment a MatrixManifold interface

### ISSUE THREAD

**Issue by kellertuer** [JuliaNLSolvers/ManifoldsBase.jl#10]
As a first and (maybe most easiest) idea to #5:
Implement a `MatrixManifold <: Manifold` with corresponding point/vector/covector types in order to

* have a matrix multiplication defined for `MatrixMPoints`
* inherit vector functions from `TVector`/`CoTVector`
* maybe even directly pass through for `rank` and such linear algebra functions?

**Comment by kellertuer** [comment]
I just noticed, it should suffice moving `ArrayManifold` here.

**Comment by mateuszbaran** [comment]
What are the benefits of having `ArrayManifold` here instead of `Manifolds.jl`?

**Comment by kellertuer** [comment]
It's an interface for people who build any `MatrixManifold` or `ArrayManifold` (more generally), that's why I would call it even an interface and put it here.

In general the question is – where does interface stop and where do (explicit) manifolds begin?
In my opinion type-wise things like `ArrayManifold` belong here,
Product & Power manifold are points of discussions for me, merely on the boundary of both.

With `ArrayManifold` here, the `DefaultManifold` is also not much more to be done with (just `<: ArrayMPoint` and such to work for points and extend the tests).

But of course I am also interested in yours and @sethaxen|s opinion on that.

**Comment by mateuszbaran** [comment]
I'm generally for keeping `ManifoldsBase.jl` small but if you think `ArrayManifold` is useful here then I'm OK with moving it. Product and power manifolds require additional dependencies so I'd keep them in `Manifolds.jl`. If someone needs them they can always make a dependency on `Manifolds.jl`.

**Comment by kellertuer** [comment]
That is a good idea to draw the line – keeping this one simple and with less dependencies.

I will do that rework now, then. We should think about also having a small documentation here, then?

**Comment by mateuszbaran** [comment]
I think we can have just one documentation linked in README for both packages with a separate section about `ManifoldsBase.jl`. It'll make documentation maintenance more simple.

**Comment by kellertuer** [comment]
One line that I removed from `ArrayManifold` is the decorator manifold pattern. We have to add that where `Manifolds.jl` defines that pattern when we transfer `Manifolds` to use the base here. Despite that this can be closed, since it's resolved. I am just finishing a few tests and add that to the PR.

**Comment by mateuszbaran** [comment]
The decorator thing is a bit problematic. Keeping it in `Manifolds.jl` makes it harder to extend it (and extensibility is the main point of having traits in the first place) but moving it here means either adding a dependency on `SimpleTraits.jl` or reworking it to plain THTT traits.

**Comment by mateuszbaran** [comment]
Yes, but `base_manifold` can only be defined for decorator manifolds and differentiating decorator manifolds from non-decorator manifolds by whether calling `base_manifold` throws an error or not is not ideal. Look at how `base_manifold` is used in `Manifolds.jl`.

I'll make a poll on slack about traits.

**Comment by mateuszbaran** [comment]
Here are poll results:

* 10 votes for pure THTT traits
* 2 votes for `SimpleTraits.jl`
* 4 votes for "something else" (but solutions that were suggested can't be applied here easily)

Given that one of the people who voted for `SimpleTraits.jl` also voted for pure THTT traits, I think the conclusion is quite clear.

**Comment by kellertuer** [comment]
Where did you do the poll? I didn't see it and hence did not participate.

Also, I've never done pure THTT traits so I don't know how that works (I would've voted for `SimpleTraits`)

**Comment by mateuszbaran** [comment]
I've made the poll in the general channel of Julia's slack. Pure THTT traits are fairly easy, it's basically that:
```julia
is_decorator_manifold(::Euclidean) = Val(false)
is_decorator_manifold(::ArrayManifold) = Val(true)
# and so on for every manifold

# and for example
function representation_size(M::Manifold)
    return representation_size(M, is_decorator_manifold(M))
end

function representation_size(M::Manifold, ::Val{true})
    return representation_size(base_manifold(M))
end

function representation_size(M::Manifold, ::Val{false})
    error("representation_size not implemented for manifold $(typeof(M)).")
end
```
That's all, basically. We have a separate function that returns objects of two or more different types and then dispatch on its result. The only downside is that it's a bit more verbose than `SimpleTraits.jl`.

**Comment by kellertuer** [comment]
And one can introduce a default using
````
is_decorator_manifold(::T) where {T <: Manifold} = Val(false)
````
right?

I think I personally prefer using `SimpleTraits`, but ok; the main remaining question for me is then:
Do we do THTT here and `SimpleTraits` for extended ones in `Manifolds`? That for me seems inconsistent.

Despite that – I think I see how to implement a decorator manifold with THTT now, thanks.

**Comment by kellertuer** [comment]
You're right – and we also do it just for 3 functions for now, I will add that and do a small PR.
