### ISSUE TITLE
Setting up CI and code coverage

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaNLSolvers/ManifoldsBase.jl#2]
We need CI and code coverage like in Manifolds.jl (issue https://github.com/JuliaNLSolvers/Manifolds.jl/issues/26 )

**Comment by mateuszbaran** [comment]
I've added AppVeyor and Travis config files. @pkofod , could you set these two services up?

**Comment by pkofod** [comment]
I will!

**Comment by mateuszbaran** [comment]
Thanks!

**Comment by mateuszbaran** [comment]
It's done so I'm closing this issue.
