### ISSUE TITLE
project_point!

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaNLSolvers/ManifoldsBase.jl#3]
At the moment `project_point!` is a little out of line because it operates on its only argument in-place while other functions generally assume that mutated output is separate. Should we change it? Or maybe provide both variants?

**Comment by sethaxen** [comment]
I'd say let's change it for consistency. I think this will also make it easier to support mutating and non-mutating variants as discussed in https://github.com/JuliaNLSolvers/Manifolds.jl/issues/42

**Comment by mateuszbaran** [comment]
In what way could it make it easier to support mutating and non-mutating variants? To me it looks like two independent issues.
