### ISSUE TITLE
What Interfaces should we include?

### ISSUE THREAD

**Issue by kellertuer** [JuliaNLSolvers/ManifoldsBase.jl#5]
I want to try to collect the interfaces we want to include here and would like to see this as a starting point for discussions. Maybe this would also be an idea to split the Package into a few files?

My first two ideas are

* metrics
* Lie groups
* embeddings (for more specific projections for example)

_edit_: For the first, I think we can take over the complete `Metric.jl` file from `Manifolds.jl` to here.

**Comment by mateuszbaran** [comment]
In the long run, we'll likely need all of these interfaces in `ManifoldsBase.jl`. Currently, though, Lie groups are a work in progress and I'm not totally sure we have the right interface for metrics (AFAIK the interface wasn't used for anything bigger). I'm also a bit reluctant to add a dependency on `SimpleTraits` to `ManifoldsBase`.

Anyway, the whole point of `ManifoldsBase.jl` is interoperability and currently other packages are only interested in projections and retractions. We can wait with moving interface specification to `ManifoldsBase.jl` until there is a package interested in using or extending that interface.

**Comment by kellertuer** [comment]
Yes, I also think, we can test  ew ideas (like Lee) “in practice” (i.e. `Manifolds.jl`) and if we have something that is working very good and fine and is general enough we move it to the general interface.
