### ISSUE TITLE
remove `Euclidean` and just provide an interface

### ISSUE THREAD

**Issue by kellertuer** [JuliaNLSolvers/ManifoldsBase.jl#6]
As just discussed in slack, I propose to delete the Euclidean manifold from this package, since this aims to _just_ provide an interface.
For testing one can still easily use the about 35 lines of code to have a default manifold equal to `Euclidean`, that should in the test maybe be called `DefaultManifold` (and for example in others, too), such that `Euclidean` is provided by `Manifolds.jl` for consistency. By calling the `DefaultManifold` as such in Tests or when others want to use `ManifoldBase` with a default, we avoid a type naming conflict.

What do you think?

**Comment by mateuszbaran** [comment]
I'm OK with removing `Euclidean` from `ManifoldsBase`. It could be a minor convenience for packages implementing our interface but since it for example forces a static dimension I can see why people would like to implement it in a different way and avoid a name conflict.
