### ISSUE TITLE
Lightweight typed data

### ISSUE THREAD

**Issue by kellertuer** [JuliaNLSolvers/ManifoldsBase.jl#9]
I would like to finish #8 with a short test of the `DefaultMPoint`, `DefaultTVector` and `DefaultCoTVector` types to illustrate that it is lightweight, both in code and data structure to enhance the semantic types.

But I somehow fail to see this easy path. As discussed in #8, I started with `similar` and `eltype` but in order to test them I noticed 2 problems, the first technical, the second philisophically.

1. In general I think one has to implement the mutating functions, for example `exp!` and `log!` to be “semantic safe”, i.e. `exp!` only works If `vto` and `v` are `<:TVector` and `x<:MPoint`.
But this requires, that for the non mutating ones, `similar` within `exp` returns a type similar to the first input (`p<:MPoint`) while `log` does not really know its resulting type (just gets two `<:MPoints` and as to somewhow “know” the `<:TVector` type. How shall we solve that? In Manopt.jl  I wrote a short function that mapped between points and tangents, which would here require to also map from tangents to cotangents.

2. Do we want to introduce hybrids, where only parts of inputs are semantically typed? If so, do we default to the non typed ones then?

**Comment by mateuszbaran** [comment]
This is why `similar_results` has so many arguments: manifold, function, and all points and vectors. The way I've overloaded this function for `VectorBundle` demonstrates the general idea: https://github.com/JuliaNLSolvers/Manifolds.jl/blob/76e628295beba375a173a997a9166351d7577c91/src/VectorBundle.jl#L172 . Whether mutating variants allow hybrid types or not is ultimately up to the person who implements a specific manifold. Sometimes it makes sense (for example wrapping vectors in a struct that describe what kind of vector that is), sometimes it doesn't. One of the great things of `similar_type` is that manifold-specific overloads are possible. For example:
```julia
similar_result(::MyManifold, ::typeof(log), ::MyMPoint, ::MyMPoint) = MyTVector()
```

**Comment by kellertuer** [comment]
Neat, I did not yet see `similar_result` that way; then – I will try to use that tomorrow :)
